Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/trusty64'

  # public ports
  # {
  #   8081 => 80,
  # }.each do |host, guest|
  #   config.vm.network :forwarded_port, guest: guest, host: host
  # end

  %w(
    docker-nginx
  ).each do |host_name|
    config.vm.define host_name do |host|

      host.vm.hostname = host_name

      # install Docker
      host.vm.provision 'docker'

    end

  end
  
end
