Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/trusty64'

  config.vm.network 'public_network'#, bridge: 'en0: Wi-Fi (AirPort)'

  %w(
      docker1
      docker2
      docker3
  ).each do |host_name|
    config.vm.define host_name do |host|

      host.vm.hostname = host_name

      # install Docker
      host.vm.provision 'docker'

    end

  end
  
end
