# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
