Vagrant.configure('2') do |config|

  config.vm.box = 'bento/ubuntu-16.04'

  %w(
    docker
  ).each do |host_name|
    config.vm.define host_name do |host|

      host.vm.hostname = host_name

      # install Docker
      host.vm.provision 'docker'

    end

  end
  
end
