Vagrant.configure('2') do |config|

  config.vm.box = 'bento/ubuntu-16.04'

  config.vm.network 'private_network', type: 'dhcp'

  %w(
    kub-1
    kub-2
  ).each do |host_name|
    config.vm.define host_name do |host|

      host.vm.hostname = host_name

      # install Docker
      host.vm.provision 'docker'

      # install Kubernetes
      host.vm.provision 'shell', :privileged => true,
        inline: <<-EOF
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
          echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
          apt-get update
          apt-get install -y kubelet kubeadm kubectl kubernetes-cni

          swapoff --all
        EOF

    end

  end
  
end
