# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foo_description'),
    ]

    operations = [
    ]
